project:
  type: website

website:
  title: "Math-Physics Paris"
  navbar:
    right:
      - text: "Home"
        href: index.qmd        
      - text: "Notes"
        href: notes.qmd
      - text: "Meetings"
        menu: 
          - text: "Seminars"
            href: Seminars/seminars.qmd
          - text: "Projects"
            href: 2/projects.qmd
      - text: "Discussions"
        menu: 
          - text: "Papers"
            href: 1/papers.qmd
          - text: "Puzzles"
            href: 3/puzzles.qmd

format:
  html:
    theme:
      light: spacelab
      dark: cyborg
    # toggle: true 
    # css: styles.css
    toc: true
    include-after-body: _include/comments.html





