project:
  type: website

website:
  title: "Math-Physics Paris"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Notes
      - href: meetings/meetings.qmd
        text: Meetings
      - href: papers/papers.qmd
        text: Papers
      - href: puzzles/puzzles.qmd
        text: Puzzles

format:
  html:
    theme:
      light: spacelab
      dark: cyborg
    toggle: true 
    css: styles.css
    toc: true
    include-after-body: _include/comments.html





