project:
  type: website

website:
  title: "Math-Physics Paris"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Lecture Notes
      - href: meetings/mp_paris.qmd
        text: Meetings

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: _include/comments.html




