---
title: "Dec 13, 2025"
---

## Speaker
Jiaxin Qiao

### Theme
Quantum Groups as Global Symmetries (2)

### Abstract
We study quantum field theories which have quantum groups as global internal symmetries. We show that in such theories operators are generically non-local, and should be thought as living at the ends of topological lines. We describe the general constraints of the quantum group symmetry, given by Ward identities, that correlation functions of the theory should satisfy. We also show that generators of the symmetry can be represented by topological lines with some novel properties. We then discuss a particular example of $U_q(\mathfrak{sl}_2)$ symmetric CFT, which we solve using the bootstrap techniques and relying on the symmetry. We finally show strong evidence that for a special value of $q$ a subsector of this theory reproduces the fermionic formulation of the Ising model. This suggests that a quantum group can act on local operators as well, however, it generically transforms them into non-local ones.

### Video  
- [Video 2025-12-13](https://drive.google.com/file/d/1co1l8CcnkwBA5PuxCGRkNBwkvm9ouwEK/view?usp=sharing)

### Notes  
- [Notes 2025-12-13](https://drive.google.com/file/d/1bgzAm4rQstF7Ay87U8uuiVb2Z9sQtmVo/view?usp=sharing)

### Resources  
- [Quantum Groups as Global Symmetries (Barak Gabai, Victor Gorbenko, Jiaxin Qiao, Bernardo Zan and Aleksandr Zhabin)](https://arxiv.org/abs/2410.24142)