---
title: "Jan 17, 2026"
---

## Speaker
Liang Kong

### Theme
Returning to the Beauty of Mathematical Structure and the Depth of Natural Philosophy

### Abstract
The world is not lacking in technical talks. There are already more than enough of them on YouTube. Instead, I would like to give a talk with no technical details, focusing on ideas rather than calculations. The talk will be interactive and aimed in particular at young people who are still early in their journey into mathematical physics. I would like to discuss several pressing questions that concern every practitioner of mathematical physics, such as how to choose one's research direction. To seriously address such questions, it is not enough to have a deep understanding of oneself; one must also develop a deep understanding of the era we live in—its defining characteristics, its challenges, and its opportunities.

### Video  
- [Video 2026-01-17](https://drive.google.com/file/d/1yvENrK_OjnDDo3fkubMW7OQBKw7hbHKx/view?usp=sharing)

### Notes  
- [Notes 2026-01-17](https://drive.google.com/file/d/17x-ntCb-hx3PbhQ-gKF5CNEA1T5hF9ZJ/view?usp=sharing)

### Resources
/