---
title: "Mar 29, 2025"
---

## Speaker
Yiyi Wan

### Theme
Chiral Anomaly

### Abstract
We began by reviewing the derivation of Noether’s theorem in classical field theory, and then introduced the Ward identity in the context of quantum field theory. Using the example of a massless Dirac fermion, we investigated the emergence of the chiral anomaly and analyzed the breaking of axial symmetry, leading to a non-vanishing divergence of the conserved current. This phenomenon is then connected to the Atiyah–Singer index theorem, allowing us to compute the partition function on a compact 4d manifold without gravity. Finally, we applied the generalized Atiyah–Patodi–Singer index theorem to extend our conclusions to the case of 3+1d topological insulators.

### Video  
[Video 2025-03-29](https://drive.google.com/file/d/17wGwReEfEpwmIfwFLKnYlqiUohgI25Eq/view?usp=sharing)

### Notes  
[Notes 2025-03-29](https://drive.google.com/file/d/1hBaoT_haQYpPokSLdMNMuocXx3WfZFH0/view?usp=sharing)

### Resources
[Gauge Theory (David Tong)](https://drive.google.com/file/d/11DanV8ZPUsgH2pw8RsFgbPP1H75IfEVg/view?usp=sharing)  
[Topological Field Theory of Time-Reversal Invariant Insulators (Xiao-Liang Qi, Taylor Hughes and Shou-Cheng Zhang)](https://drive.google.com/file/d/1zO3u1xZheRVJbgAj1p6wjgqGEW9wcbdx/view?usp=sharing)