---
title: "Meetings"
---

- [Mar 15, 2025: Axiomatic Construction of TQFT](mar-15-2025.qmd)  
- [Mar 16, 2025: Meet & Greet Session](mar-16-2025.qmd)  
- [Mar 22, 2025: Basic Concepts of Higher-form Symmetries & Yang-Mills Theory](mar-22-2025.qmd)  
- [Mar 29, 2025: Chiral Anomaly](mar-29-2025.qmd)  
- [Apr 05, 2025: 't Hooft Anomaly](apr-05-2025.qmd)  
- [Apr 06, 2025: Leptogenesis](apr-06-2025.qmd)  
- [Apr 12, 2025: Homology Theory & Replica Method](apr-12-2025.qmd)   
- [Apr 13, 2025: Leptogenesis and Sakharov Conditions](apr-13-2025.qmd)  
- [Apr 19, 2025: Chern-Weil Theorem & Characteristic Classes](apr-19-2025.qmd) 
- [Apr 22, 2025: Atiyah-Singer Index Theorem](apr-22-2025.qmd)  
- [May 06, 2025: Wess-Zumino Condition ](may-06-2025.qmd)  
- [May 10, 2025: Topological K-theory](may-10-2025.qmd)  
- [May 17, 2025: SPT Construction](may-17-2025.qmd)  
- [May 24, 2025: Instanton](may-24-2025.qmd)  
- [Jun 07, 2025: SymTFT](jun-07-2025.qmd)  
- [Jun 15, 2025: Non-invertible Symmetries in 4d](jun-15-2025.qmd)  
- [Jul 12, 2025: WKB Method and Symplectic Geometry](jul-12-2025.qmd)  
- [Jul 20, 2025: Quantizable Condition and Maslov Technique](jul-20-2025.qmd)
- [Jul 26, 2025: A Complete Geometric Characterization of Quantizability](jul-26-2025.qmd)
- [Aug 02, 2025: Differential Operators on Manifolds](aug-02-2025.qmd)
- [Aug 04, 2025: Anomaly Coefficients: Continuous vs Discrete Symmetry](aug-04-2025.qmd)
