---
title: "Categorical Symmetry of the Standard Model from Gravitational Anomaly"
---

## Author

Pavel Putrov, Juven Wang

### Abstract

In the Standard Model, some combination of the baryon $\mathbf{B}$ and lepton $\mathbf{L}$ number symmetry is free of mixed anomalies with strong and electroweak $su(3) \times su(2) \times u(1)_{\tilde{Y}}$ gauge forces. However, it can still suffer from a mixed gravitational anomaly, hypothetically pertinent to leptogenesis in the very early universe. This happens when the total "sterile right-handed" neutrino number $n_{\nu_R}$ is not equal to the family number $N_f$. Thus the invertible $\mathbf{B} - \mathbf{L}$ symmetry current conservation can be violated quantum mechanically by gravitational backgrounds such as gravitational instantons. In specific, we show that a noninvertible categorical $\mathbf{B} - \mathbf{L}$ generalized symmetry still survives in gravitational backgrounds. In general, we propose a construction of noninvertible symmetry charge operators as topological defects derived from invertible anomalous symmetries that suffer from mixed gravitational anomalies. Examples include the perturbative local and nonperturbative global anomalies classified by $\mathbb{Z}$ and $\mathbb{Z}_{16}$ respectively. For this construction, we utilize the anomaly inflow bulk-boundary correspondence, the 4d Pontryagin class and the gravitational Chern-Simons 3-form, the 3d Witten–Reshetikhin–Turaev-type topological quantum field theory with a framing anomaly corresponding to a 2d rational conformal field theory with an appropriate rational chiral central charge, and the 4d $\mathbb{Z}_4^{\mathrm{TF}}$-time-reversal symmetric topological superconductor with 3d boundary topological order.

### Link

[Categorical Symmetry of the Standard Model from Gravitational Anomaly (Pavel Putrov, Juven Wang)](https://arxiv.org/abs/2302.14862)